### ISSUE TITLE
inconsistent prototypes in subject.md

### ISSUE THREAD

**Issue by KrolPolski** [juliuskoskela/c-vec#11]
In your vec.c file there are two functions prototyped like this:
```
int vec_filter(t_vec *dst, t_vec *src, bool (*f) (void *))
int vec_reduce(void *dst, t_vec *src, void (*f) (void *, void *))
```
But on the subject.md they are prototyped like this:
```
void vec_filter(t_vec *dst, t_vec *src, bool (*f) (void *));
void vec_reduce(void *acc, t_vec *src, void (*f) (void *, void *));
```
Having the int return type is more useful for catching errors, so I would recommend updating the subject.md to match your actual implementation in vec.c.

**Comment by juliuskoskela** [comment]
Thank you for pointing out the issue! Feel free to fork the repository and create a pull request with the required corrections and I'll merge it :)
