### ISSUE TITLE
Typo in header for vec_new

### ISSUE THREAD

**Issue by Caruychen** [juliuskoskela/c-vec#2]
There's a mismatch in the naming convention for the src/dst parameters in vec_new.

In the exercise: https://github.com/juliuskoskela/c-vec/blob/main/subject.md#ex0-vec_new
The parameters are named dst and init_alloc, but the corresponding parameters are named src and len in the header https://github.com/juliuskoskela/c-vec/blob/main/subject.md#ex0-vec_new

**Comment by juliuskoskela** [comment]
Good catch!

**Comment by juliuskoskela** [comment]
Typos corrected
